### ISSUE TITLE
website crash to 500 error

### ISSUE THREAD

**Issue by KellerPT** [flowdee/woo-mailerlite#6]
website crash to 500 error after activate plugin

how can i fix it?

**Comment by bielen2k** [comment]
I have the same problem, plugin don't works :/

@KellerPT 
To restore the page, delete the woo-mailerlite directory from the wp-content / plugins directory

**Comment by bielen2k** [comment]
I found a solution. PHP min. 5.6 is required :)

**Comment by flowdee** [comment]
in general it should work with PHP 5.3+ fine too. In order to get an idea of the problem, I need some entries out of the WP debug log @KellerPT. Therefore please edit your wp-config.php, search for “WP_DEBUG” and update the line as follows:

define( ‘WP_DEBUG’, true );
define( ‘WP_DEBUG_LOG’, true );
define( ‘WP_DEBUG_DISPLAY’, false );

Afterwards please re-produce the issue by activating the plugin. Now you will find a “debug.log” file in your wp-content/ directory which can be uploaded or sent to me directly.

Without some error logs, I can’t fix an error 🙂

**Comment by flowdee** [comment]
Closed due to missing error reportings
